### ISSUE TITLE
Activity notifications

### ISSUE THREAD

**Issue by orschiro** [hypothesis/wp-hypothesis#11]
Dear all, 

Thank you very much for your work on this excellent plugin!

I want to use hypothesis to allow users on a Wordpress blog to add extra information to a text. 

It would be great if I as the blog owner could receive a notification if someone has added a note or annotation highlight. 

Is this technically possible?

Thankfully,

Robert

**Comment by acelaya** [comment]
To be tracked in https://github.com/hypothesis/client if this becomes a priority.
