### ISSUE TITLE
Moderation queue or restricted access to annotate

### ISSUE THREAD

**Issue by forteller** [hypothesis/wp-hypothesis#15]
Love your work!

I would like to use this plugin on a WP page with a longer text to add my own annotations to the text and let some others help out with the annotations, without letting the whole world add to it.

I guess this is not perfectly within your scope, but I don't know of any other tool that would work better for this. All I need is for you to add an option to let me choose either:
1) that all new annotations be put in a moderation queue for the site owner to allow or deny before they are published, or
2) only let specific Hypothesis accounts annotate a specific WP page.

Would this be possible?

Thank you!

**Comment by robertknight** [comment]
Hello,

I'm afraid Hypothesis does not currently support either of these features, but we do have some closely related requests from other users. Specifically:

- We have users who are interested in pre-moderation (ie. a moderation queue of some sort)
- We have users who are interested in being able to control which "channel" (or Group) is shown by default, and a kind of group which users have to be invited to before they can annotate in.

I cannot promise when either of these will be implemented yet, but we post about product updates on our blog at https://web.hypothes.is/blog/

**Comment by forteller** [comment]
So, this is not about creating a moderation queue? https://twitter.com/dr_jdean/status/887401832582062081

Or is it the pre-moderation thing you mentioned? Any ETA on this?

Thanks!

**Comment by acelaya** [comment]
We currently support flagging annotations, and there are plans to support more moderation controls eventually.

Closing this though, as that would not be exclusive to the WordPress plugin.
