### ISSUE TITLE
Contributing upstream?

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/wp-hypothesis#2]
First, thanks for developing this plugin!

Second, Hypothesis would like to continue work on this project, and use your existing foundation as a base. For us to do that well, I wanted to ask if you could do two things:
1. would you be open to moving ownership of this plugin to the hypothesis org here at GitHub?
2. would you (relatedly) be open to licensing it under the BSD?

You're also welcome to sign our [Contributors License Agreement](https://github.com/hypothesis/h/blob/master/CONTRIBUTING.rst#licensing), but I'm not sure that's necessary in this case.

Thanks, @timmmmyboy!

Also, @dwhly says "hi" :smile:

**Comment by timmmmyboy** [comment]
Checking back in on this it looks like the transfer to you is still pending. Are you all still interested in assuming ownership of the plugin? If so you can accept the transfer of the repo and then transfer it to your org. Also need a Wordpress.org account that you all would like to use to make you author in the plugin repository.

**Comment by BigBlueHat** [comment]
@timmmmyboy very strange... Can you try the transfer again?

Use `BigBlueHat` for the WordPress.org account also. I'm trying to figure out if we "own" the `hypothesis` account there or not... Password reminders are going...somewhere...

**Comment by timmmmyboy** [comment]
Aborted it and restarted and it says pending. BigBlueHat is now added as a committer to the WP plugin though so that should work (may be other options to enable more "ownership" there but that should at least allow you full access to update the plugin without any work on my end).

**Comment by BigBlueHat** [comment]
k. Looks like I'm in on WordPress.org. No idea on the transfer request. @tilgovi may be able to help here.

If that still doesn't work, perhaps you can transfer it to me personally, and I can try to transfer it to the Hypothesis org.

We'll get it sorted! :smiley: Thanks.

**Comment by tilgovi** [comment]
@BigBlueHat reading the backlog here I was pretty sure it was getting transfered to you personally. However, maybe it makes more sense to transfer it to me, since I can transfer it to the org account.

**Comment by timmmmyboy** [comment]
Yeah, I was indeed trying to transfer it to your account @BigBlueHat but I just tried @tilgovi as well. As long as someone who is a part of the Hypothesis org owns it they can transfer it in there.

**Comment by tilgovi** [comment]
Transfered. https://github.com/hypothesis/wp-hypothesis

**Comment by tilgovi** [comment]
Here's some info on license: http://codex.wordpress.org/Writing_a_Plugin#License
So, BSD is fine.

**Comment by timmmmyboy** [comment]
Awesome! Thanks for getting that all figured out! (and good to know about BSD being compatible with WP)

**Comment by BigBlueHat** [comment]
Great work @tilgovi! @timmmmyboy any objections to us using BSD for this?

Pretty sure you're OK with it but it's best to have stuff like this stated in writing. :smiley_cat:

**Comment by timmmmyboy** [comment]
Yes please feel free to adjust the license to BSD :)

**Comment by BigBlueHat** [comment]
Thanks again @timmmmyboy :smile:

**Comment by timmmmyboy** [comment]
Quite welcome!

**Comment by dwhly** [comment]
@timmmmyboy Hey!  Long time.  Can you ping me at dwhaley@ hypothes.is?  We'd like to work to get the WP plugin recertified and back in action.  I think you're the current owner of the WP acct?  cc @mkdir-washington-edu

**Comment by mkdir-washington-edu** [comment]
@timmmmyboy If you could add me as a contributor on the project I can get other folks added as needed.

Our request isn't specific to this thread. There's a somewhat-recent message on the plugin page saying "This plugin has been closed as of January 28, 2022 and is not available for download. Reason: Guideline Violation." and we didn't know how else to get in touch with the folks on the project in order to assist.

Sorry to hijack a closed thread.

**Comment by greatislander** [comment]
Hi all, could you remove me from the plugin team on WordPress.org? Thanks.
