### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by danicotillas** [hypothesis/wp-hypothesis#25]
Where could I translate all the strings of the plugin to spanish? Not only the ones of the adjustments area.

Thanks

**Comment by robertknight** [comment]
Hello,

The [Hypothesis client](https://github.com/hypothesis/client), which is the piece of software that actually displays annotations, does not currently support translation to other languages I'm afraid. For updates on future improvements in this area, please subscribe to [this GitHub issue](https://github.com/hypothesis/product-backlog/issues/324).

**Comment by acelaya** [comment]
To be tracked in the issue Rob mentioned above. Closing this.
