### ISSUE TITLE
the path to the upload folder needs to be a setting

### ISSUE THREAD

**Issue by judell** [hypothesis/wp-hypothesis#28]
The PDF feature works by prepending https://via.hypothes.is to links in posts that point into the media upload folder, by default wp-content/uploads. But if your WP system refers to a different place, you're out of luck. So, the path to that folder should be a setting.

**Comment by greatislander** [comment]
Hi @judell! You should be able to use [`wp_upload_dir()['basedir']`](https://developer.wordpress.org/reference/functions/wp_upload_dir/) to get the correct `/uploads` path on any system.

**Comment by judell** [comment]
Aha. Thanks Ned!

**Comment by greatislander** [comment]
Fixed by #27, I think!

**Comment by acelaya** [comment]
Closing as fixed
