### ISSUE TITLE
Select which pages hypothes.is should / should not be on

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/wp-hypothesis#3]

**Comment by JakeHartnell** [comment]
Addressed with #5 and https://github.com/hypothesis/wp-hypothesis/commit/eb56706ad7d745df671394bb7335a457d15f57ce

**Comment by JakeHartnell** [comment]
@BigBlueHat / @judell, I've tested this on my local machine and it should be ready for @jeremydean. I don't know what we need to do to cut a new release, but Jeremy wanted to have this out by August 10th.

**Comment by jeremydean** [comment]
psyched about this. thanks, jake. now let's do this for drupal!
ᐧ

On Wed, Aug 5, 2015 at 8:19 PM, Jake Hartnell <notifications@github.com>
wrote:

> @BigBlueHat <https://github.com/BigBlueHat> / @judell
> <https://github.com/judell>, I've tested this on my local machine and it
> should be ready for @jeremydean <https://github.com/jeremydean>. I don't
> know what we need to do to cut a new release, but Jeremy wanted to have
> this out by August 10th.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hypothesis/wp-hypothesis/issues/3#issuecomment-128200120>
> .
>



-- 
Dr. Jeremy Dean
Director of Education

**Comment by jeremydean** [comment]
can you all let me know when this is released so that i can inform partner?
ᐧ

On Wed, Aug 5, 2015 at 10:01 PM, Jeremy Dean <jeremydean@hypothes.is> wrote:

> psyched about this. thanks, jake. now let's do this for drupal!
> ᐧ
>
> On Wed, Aug 5, 2015 at 8:19 PM, Jake Hartnell <notifications@github.com>
> wrote:
>
>> @BigBlueHat <https://github.com/BigBlueHat> / @judell
>> <https://github.com/judell>, I've tested this on my local machine and it
>> should be ready for @jeremydean <https://github.com/jeremydean>. I don't
>> know what we need to do to cut a new release, but Jeremy wanted to have
>> this out by August 10th.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hypothesis/wp-hypothesis/issues/3#issuecomment-128200120>
>> .
>>
>
>
>
> --
> Dr. Jeremy Dean
> Director of Education
>



-- 
Dr. Jeremy Dean
Director of Education

**Comment by BigBlueHat** [comment]
@jeremydean now OK? https://wordpress.org/plugins/hypothesis/changelog/

:smile:
