### ISSUE TITLE
Updating knowledge base documentation - quick start guide and PDFs

### ISSUE THREAD

**Issue by klemay** [hypothesis/wp-hypothesis#30]
- [ ] use Jeremy's educator guide as a template for creating KBase article on PDFs
- [ ] edit existing "quick start guide" to make clearer

this task comes out of Zendesk metrics for Jan 2018, where these two topics generated the most user requests

**Comment by xolotl** [comment]
@klemay: If this issue pertains to the current Hypothesis website, it should probably go in a different repository:
https://github.com/hypothesis/webhypothesis

It's confusing, but this repository is for the WordPress plugin for Hypothesis, not the Hypothesis website running on WordPress ;)

**Comment by klemay** [comment]
Got it - closing & creating new issue in appropriate repo!
