### ISSUE TITLE
lack of updates making people hesitate to install plugin

### ISSUE THREAD

**Issue by klemay** [hypothesis/wp-hypothesis#32]
Placeholder for now - but I've gotten a number of tickets in support asking us if the plugin is defunct because it hasn't been updated in >3yrs. Common "wisdom" in the WP community is to only install plugins with recent updates. We might consider a somewhat frequent update schedule going forward.

**Comment by greatislander** [comment]
@klemay :+1: This could be as simple as bumping the "Tested up to" version to current releases of WordPress for starters.

**Comment by judell** [comment]
Update: We are working with @greatislander to regain the ability to deploy the WP plugin.

**Comment by greatislander** [comment]
@klemay Updated, and the deployment to WordPress.org will now happen automatically whenever the version number is changed in https://github.com/hypothesis/wp-hypothesis/blob/master/hypothesis.php.

**Comment by judell** [comment]
Thanks so much, Ned!

**Comment by klemay** [comment]
Yes, thanks x1 million!

**Comment by caraya** [comment]
The latest updated version is 5.2. Can we bump it to a newer version?
