### ISSUE TITLE
Include PDF.js viewer

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/wp-hypothesis#4]
For optional PDF + annotation viewing:
http://github.com/hypothesis/pdf.js-hypothes.is/

**Comment by robertknight** [comment]
According to https://hyp.is/3CGK8ndHEeeyK0M4BZ7owg/web.hypothes.is/installing-the-hypothes-is-wordpress-plugin/ the WordPress plugin now supports PDFs.

Let me know if there was anything else implied by the original issue which is not yet implemented.
