### ISSUE TITLE
allow users to choose configurations for h in WP

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/wp-hypothesis#7]
following @JakeHartnell great update that allows you do add hypothes.is to specific pages in a WP instance, i think it would be great to allow them to choose how h appears as well: 

sidebar default open/closed
highlights default visible/in-

**Comment by dwhly** [comment]
> sidebar default open/closed
> highlights default visible/in-

+ 1 
We should have a standard set of configurable params here.  That's probably in your camp @judell.

**Comment by robertknight** [comment]
According to https://web.hypothes.is/installing-the-hypothes-is-wordpress-plugin/ this is now implemented, at least for the two options described in the initial issue description.
